name: Run CI

on:
  schedule:
    - cron: '0 9 * * 0' # Run every Sunday at 9am UTC
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


defaults:
  run:
    shell: bash -l {0}


jobs:
  run_ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "date=$(date +%Y-%m-%d)" >> "${GITHUB_OUTPUT}"
      
      - name: Setup Conda Environment
        uses: mamba-org/setup-micromamba
        with:
          environment-file: environment.yaml
          environment-name: joint_demo
          cache-environment: true
          cache-downloads: true
          cache-environment-key: environment-${{ steps.date.outputs.date }}
          cache-downloads-key: downloads-${{ steps.date.outputs.date }}
          create-args: >-
            python==3.12


      - name: Setup kernel
        run: |
          python -m ipykernel install --user --name joint_demo

      - name: Run papermill
        run: |
          papermill joint_demo.ipynb hindsight_executed.ipynb  -k joint_demo  --execution-timeout -1

      - name: Echo done 
        run: echo "Done running papermill on joint_demo.ipynb"
